import { BsFiletypeHtml, BsFiletypeCss, BsBootstrap, BsDatabase } from "react-icons/bs";
import { FaNodeJs, FaAndroid, FaJava, FaPython } from "react-icons/fa";
import {
  SiJavascript,
  SiReact,
  SiMongodb,
  SiMysql,
  SiTypescript,
  SiGithub,
  SiFirebase,
  SiDocker,
  SiExpress,
  SiAngular,
  SiTensorflow,
  SiPytorch,
  SiKeras,
  SiScikitlearn,
  SiFlask,
  SiFastapi,
  SiSpringboot,
  SiHuggingface,
  SiMicrosoftazure,
  SiOpenai,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";

export const TechstackList = [
  {
    _id: 25,
    name: "Azure AI Foundry",
    icon: SiMicrosoftazure,
    class: "AzureAI",
  },
  {
    _id: 26,
    name: "OpenAI",
    icon: SiOpenai,
    class: "OpenAI",
  },
  {
    _id: 27,
    name: "Hugging Face",
    icon: SiHuggingface,
    class: "HuggingFace",
  },
  {
    _id: 28,
    name: "FAISS / Vector DBs",
    icon: BsDatabase,
    class: "FAISS",
  },
  {
    _id: 29,
    name: "FastAPI",
    icon: SiFastapi,
    class: "FastAPI",
  },
  {
    _id: 1,
    name: "HTML",
    icon: BsFiletypeHtml,
    class: "HTML",
  },
  {
    _id: 2,
    name: "CSS / SCSS",
    icon: BsFiletypeCss,
    class: "CSS",
  },
  {
    _id: 3,
    name: "Bootstrap",
    icon: BsBootstrap,
    class: "Bootstrap",
  },
  {
    _id: 4,
    name: "JavaScript",
    icon: SiJavascript,
    class: "JavaScript",
  },
  {
    _id: 5,
    name: "TypeScript",
    icon: SiTypescript,
    class: "TypeScript",
  },
  {
    _id: 6,
    name: "Angular",
    icon: SiAngular,
    class: "Angular",
  },
  {
    _id: 7,
    name: "React JS",
    icon: SiReact,
    class: "React",
  },
  {
    _id: 8,
    name: "Android Dev",
    icon: FaAndroid,
    class: "Android",
  },
  {
    _id: 9,
    name: "Java",
    icon: FaJava,
    class: "Java",
  },
  {
    _id: 10,
    name: "Python",
    icon: FaPython,
    class: "Python",
  },
  {
    _id: 11,
    name: "Node JS",
    icon: FaNodeJs,
    class: "NodeJs",
  },
  {
    _id: 12,
    name: "Express JS",
    icon: SiExpress,
    class: "Express",
  },
  {
    _id: 13,
    name: "MongoDB",
    icon: SiMongodb,
    class: "MongoDB",
  },
  {
    _id: 14,
    name: "SQL",
    icon: SiMysql,
    class: "SQL",
  },
  {
    _id: 15,
    name: "Firebase",
    icon: SiFirebase,
    class: "Firebase",
  },
  {
    _id: 16,
    name: "Git / Github",
    icon: SiGithub,
    class: "GitHub",
  },
  {
    _id: 17,
    name: "Docker",
    icon: SiDocker,
    class: "Docker",
  },
  {
    _id: 18,
    name: "AWS",
    icon: FaAws,
    class: "AWS",
  },
  {
    _id: 19,
    name: "TensorFlow",
    icon: SiTensorflow,
    class: "TensorFlow",
  },
  {
    _id: 20,
    name: "PyTorch",
    icon: SiPytorch,
    class: "PyTorch",
  },
  {
    _id: 21,
    name: "Keras",
    icon: SiKeras,
    class: "Keras",
  },
  {
    _id: 22,
    name: "Scikit-learn",
    icon: SiScikitlearn,
    class: "ScikitLearn",
  },
  {
    _id: 23,
    name: "Spring Boot",
    icon: SiSpringboot,
    class: "SpringBoot",
  },
  {
    _id: 24,
    name: "Flask",
    icon: SiFlask,
    class: "Flask",
  },
];
