name: Deploy Portfolio App to EC2

on:
  push:
    branches:
      - main   # change if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ SSH deploy to EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying Portfolio App on EC2..."

            # Navigate to app folder
            cd ~/app

            # Reset code to match GitHub
            git fetch origin main
            git reset --hard origin/main

            # Install backend dependencies
            npm install --legacy-peer-deps

            # Build frontend
            cd client
            npm install --legacy-peer-deps
            npm run build
            cd ..

            # Restart Node app with PM2
            pm2 restart portfolio-app || pm2 start server.js --name portfolio-app

            echo "Deployment complete!"

